// <auto-generated />
using System;
using LootLoOnline.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LootLoOnline.Business.Migrations
{
    [DbContext(typeof(LootLoOnlineDbContext))]
    partial class LootLoOnlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LootLoOnline.Business.Models.DealsOfTheDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("imageUrls_default")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrls_low")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrls_mid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DealsOfTheDays");
                });

            modelBuilder.Entity("LootLoOnline.Business.Models.OfferProduct", b =>
                {
                    b.Property<string>("productId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsUpdated")
                        .HasColumnType("bit");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpecialPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("attributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("booksInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categoryPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("codAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detailedSpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("discountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("estimatedDeliveryTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrls_200")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrls_400")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrls_800")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("inStock")
                        .HasColumnType("bit");

                    b.Property<string>("keySpecs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lifeStyleInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("maximumRetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("offers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productBrand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("sellerAverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("sellerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("sellerNoOfRatings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellerNoOfReviews")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("shippingCharges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("shotTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("specificationList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("validTill")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.ToTable("OfferProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
